### ISSUE TITLE
[reVC] Shakedown crash

### ISSUE THREAD

**Issue by BreakinBenny** [GTAmodding/re3#1332]
**Describe the bug**
In the first Vercetti Estate mission **Shakedown**, upon shooting some glass panels the game crashes with this:
`Assertion failed!
File: ..\src\core\Lists.cpp
Line: 20
Function: CEntryInfoNode::operator new
Expression: node

(Press Retry to debug the application)`

And when it doesn't, my game just crashes without an error message.

**To Reproduce**
Start the Shakedown job, then get to the mall and shoot some glass or move around it a good bit; your game should close unceremoniously or print the above error. I can't tell whether this happens even outside Shakedown.

**Expected behavior**
The issue should not happen at all. When my game crashes, I can't take a screenshot at all.

**Version**
Windows OpelGL 64bit OAL 355c260

**Comment by ttyborg** [comment]
I can also confirm this crash happening on Linux as of 4b747e5.
It happens during freeroam as well, so it is not tied to being on a mission.

Using GDB I also got this, hope it helps:

```
#0  0x0000555555777959 in CEntryInfoList::InsertItem (sect=0x555555d464c0 <CWorld::ms_aSectors+394880>, listnode=<optimized out>, list=0x555555d464d0 <CWorld::ms_aSectors+394896>, this=0x55555a7f9b60) at ../src/core/Lists.h:107
#1  CPhysical::Add (this=0x55555a7f9a70) at ../src/entities/Physical.cpp:142
#2  0x000055555586288b in CWorld::Add (ent=ent@entry=0x55555a7f9a70) at ../src/core/World.cpp:73
#3  0x000055555569bab8 in CEscalator::Update (this=0x555555a079c0 <CEscalators::aEscalators+704>) at ../src/renderer/Fluff.cpp:974
#4  0x000055555569bbbf in CEscalators::Update () at ../src/renderer/Fluff.cpp:1127
#5  CEscalators::Update () at ../src/renderer/Fluff.cpp:1122
#6  CMovingThings::Update () at ../src/renderer/Fluff.cpp:442
#7  0x00005555556c54c8 in CGame::Process () at ../src/core/Game.cpp:927
#8  0x0000555555887fe6 in Idle (arg=0x1) at ../src/core/main.cpp:1540
#9  0x0000555555888a08 in AppEventHandler (event=<optimized out>, param=0x1) at ../src/core/main.cpp:1784
#10 0x00005555558a30a0 in RsEventHandler (event=rsIDLE, param=0x1) at ../src/skel/skeleton.cpp:210
#11 0x0000555555581b21 in main (argc=<optimized out>, argv=<optimized out>) at ../src/skel/glfw/glfw.cpp:2330
```

**Comment by Rugaliz** [comment]
Can confirm that I'm having the same issue.
Fedora Linux 34 OpenGl

**Comment by gjk-23** [comment]
Could it be that you set Ped density to max? It always crashes for me with the ped density set to max when I'm in the mall. I have to turn the bars down half way before going into the mall.

**Comment by BreakinBenny** [comment]
> Could it be that you set Ped density to max? It always crashes for me with the ped density set to max when I'm in the mall. I have to turn the bars down half way before going into the mall.
Maybe. I maxed both that and the car density when I played, which is also definitely why I saw very few gang members spawn during particular Rampages.
