### ISSUE TITLE
Crash when starting new game [Linux release build amd64]

### ISSUE THREAD

**Issue by ShFil119** [GTAmodding/re3#712]
```
=================================================================
==85506==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffe1ea5cd00 at pc 0x5572331918e5 bp 0x7ffe1ea5ccb0 sp 0x7ffe1ea5cca0
READ of size 64 at 0x7ffe1ea5cd00 thread T0
    #0 0x5572331918e4 in rw::convMatrix(rw::RawMatrix*, rw::Matrix*) ../vendor/librw/src/gl/../rwbase.h:375
    #1 0x5572331918e4 in rw::gl3::setWorldMatrix(rw::Matrix*) ../vendor/librw/src/gl/gl3device.cpp:801
    #2 0x557233194c51 in rw::gl3::im3DTransform(void*, int, rw::Matrix*, unsigned int) ../vendor/librw/src/gl/gl3immed.cpp:263
    #3 0x557233135359 in RwIm3DTransform(rw::gl3::Im3DVertex*, unsigned int, rw::Matrix*, unsigned int) ../src/fakerw/fake.cpp:448
    #4 0x5572330b630f in CWaterLevel::RenderAndEmptyRenderBuffer() ../src/render/WaterLevel.cpp:1144
    #5 0x5572330b6a32 in CWaterLevel::RenderOneFlatSmallWaterPoly(float, float, float, rw::RGBA const&) ../src/render/WaterLevel.cpp:771
    #6 0x5572330bae2d in CWaterLevel::RenderWater() ../src/render/WaterLevel.cpp:538
    #7 0x5572331439d0 in RenderScene() ../src/core/main.cpp:866
    #8 0x5572331439d0 in Idle(void*) ../src/core/main.cpp:1139
    #9 0x557233144117 in AppEventHandler ../src/core/main.cpp:1313
    #10 0x55723315051f in RsEventHandler ../src/skel/skeleton.cpp:212
    #11 0x557232a8a66c in main ../src/skel/glfw/glfw.cpp:1732
    #12 0x7f466edde151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
    #13 0x557232a8caad in _start (/run/media/filip/6C862B68862B31CE/Users/shfil/Documents/Grand Theft Auto 3/re3+0xd1aad)

Address 0x7ffe1ea5cd00 is located in stack of thread T0 at offset 32 in frame
    #0 0x557233194bcf in rw::gl3::im3DTransform(void*, int, rw::Matrix*, unsigned int) ../vendor/librw/src/gl/gl3immed.cpp:257

  This frame has 1 object(s):
    [32, 96) 'ident' (line 259) <== Memory access at offset 32 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope ../vendor/librw/src/gl/../rwbase.h:375 in rw::convMatrix(rw::RawMatrix*, rw::Matrix*)
Shadow bytes around the buggy address:
  0x100043d43950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d43960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d43970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d43980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d43990: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x100043d439a0:[f8]f8 f8 f8 f8 f8 f8 f8 f3 f3 f3 f3 00 00 00 00
  0x100043d439b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d439c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d439d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d439e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d439f0: f1 f1 f1 f1 f1 f1 04 f2 00 f2 f2 f2 00 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==85506==ABORTING
```

**Comment by erorcun** [comment]
fixed via https://github.com/aap/librw/commit/edc77742c512b85ad35544b2cfbe3f359dc75805
