### ISSUE TITLE
[reVC] Crash during Demolition Man

### ISSUE THREAD

**Issue by hazelnot** [GTAmodding/re3#790]
The game crashes at the end of Demolition Man, during the cutscene where the building explodes.

Edit: Here's the crash log:
```
Error: No particle objects available!

Thread 1 "reVC" received signal SIGSEGV, Segmentation fault.
CFire::ProcessFire (this=this@entry=0x555555928778 <gFireManager+120>) at ../src/math/Matrix.h:38
38		CVector& GetPosition(void) { return *(CVector*)&m_matrix.pos; }
(gdb) bt
#0  CFire::ProcessFire (this=this@entry=0x555555928778 <gFireManager+120>) at ../src/math/Matrix.h:38
#1  0x0000555555635ca2 in CFireManager::Update (this=0x555555928700 <gFireManager>) at ../src/core/Fire.cpp:316
#2  0x0000555555658d63 in CGame::Process () at ../src/core/Game.cpp:765
#3  0x00005555557c42b4 in Idle (arg=arg@entry=0x1) at ../src/core/main.cpp:1020
#4  0x00005555557c4a28 in AppEventHandler (event=event@entry=rsIDLE, param=param@entry=0x1) at ../src/core/main.cpp:1246
#5  0x00005555557cbda0 in RsEventHandler (event=rsIDLE, param=0x1) at ../src/skel/skeleton.cpp:212
#6  0x0000555555578e1c in main (argc=<optimized out>, argv=0x7fffffffe6e8) at ../src/skel/glfw/glfw.cpp:1870
```

**Comment by TheOfficialFloW** [comment]
Should be fixed with: https://github.com/GTAmodding/re3/commit/1a8a1c91cb30d592e8f46c9b45f663e2ad82ed5c
