### ISSUE TITLE
malloc(): invalid size (unsorted)

### ISSUE THREAD

**Issue by kattjevfel** [GTAmodding/re3#813]
Since 546ed0ff07cad63cb07612d8aff8d63213f71ecd re3 will crash right as you start a new save / load an existing save.

config=debug_linux-amd64-librw_gl3_glfw-oal
Output: https://gist.github.com/kattjevfel/0dbc431832c081ae87cef204194ffcde

backtrace:
```gdb
(gdb) bt
#0  0x00007f9ca3a4e615 in raise () from /usr/lib/libc.so.6
#1  0x00007f9ca3a37862 in abort () from /usr/lib/libc.so.6
#2  0x00007f9ca3a905e8 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f9ca3a9827a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f9ca3a9b66c in _int_malloc () from /usr/lib/libc.so.6
#5  0x00007f9ca3a9dad5 in calloc () from /usr/lib/libc.so.6
#6  0x00007f9ca1afbe74 in ?? () from /usr/lib/dri/radeonsi_dri.so
#7  0x00007f9ca1b00c2a in ?? () from /usr/lib/dri/radeonsi_dri.so
#8  0x00007f9ca1ae7b29 in ?? () from /usr/lib/dri/radeonsi_dri.so
#9  0x00007f9ca20e881f in ?? () from /usr/lib/dri/radeonsi_dri.so
#10 0x00007f9ca1dc1d8a in ?? () from /usr/lib/dri/radeonsi_dri.so
#11 0x00007f9ca215843d in ?? () from /usr/lib/dri/radeonsi_dri.so
#12 0x00007f9ca13f8e54 in ?? () from /usr/lib/dri/radeonsi_dri.so
#13 0x00007f9ca13fd2ef in ?? () from /usr/lib/dri/radeonsi_dri.so
#14 0x00007f9ca13feee3 in ?? () from /usr/lib/dri/radeonsi_dri.so
#15 0x00007f9ca15972cd in ?? () from /usr/lib/dri/radeonsi_dri.so
#16 0x00007f9ca159737e in ?? () from /usr/lib/dri/radeonsi_dri.so
#17 0x000055c82d3b1e5a in rw::gl3::rasterUnlock (raster=0x55c82f7ec960, level=0) at ../vendor/librw/src/gl/gl3raster.cpp:485
#18 0x000055c82d3cabdb in rw::Raster::unlock (this=0x55c82f7ec960, level=0) at ../vendor/librw/src/raster.cpp:112
#19 0x000055c82d3b2a4f in rw::gl3::readNativeTexture (stream=0x55c82fc0bd30) at ../vendor/librw/src/gl/gl3raster.cpp:787
#20 0x000055c82d3cedbb in rw::Texture::streamReadNative (stream=0x55c82fc0bd30) at ../vendor/librw/src/texture.cpp:481
#21 0x000055c82d37a830 in rwNativeTextureHackRead (stream=0x55c82fc0bd30, tex=0x7ffec5d1e870, size=12408) at ../src/fakerw/fake.cpp:300
#22 0x000055c82d32fb10 in RwTextureGtaStreamRead (stream=0x55c82fc0bd30) at ../src/rw/TexRead.cpp:43
#23 0x000055c82d32fce2 in RwTexDictionaryGtaStreamRead (stream=0x55c82fc0bd30) at ../src/rw/TexRead.cpp:78
#24 0x000055c82d33bd1d in CTxdStore::LoadTxd (slot=29, stream=0x55c82fc0bd30) at ../src/rw/TxdStore.cpp:132
#25 0x000055c82d327ad6 in CStreaming::ConvertBufferToObject (buf=0x55c82fc83000 "\026", streamId=5529) at ../src/core/Streaming.cpp:514
#26 0x000055c82d32b958 in CStreaming::LoadAllRequestedModels (priority=false) at ../src/core/Streaming.cpp:1975
#27 0x000055c82d1ee055 in CGame::Initialise (datFile=0x55c82d454a0c "DATA\\GTA3.DAT") at ../src/core/Game.cpp:404
#28 0x000055c82d383b4f in InitialiseGame () at ../src/core/main.cpp:1239
#29 0x000055c82d37fe5d in main (argc=1, argv=0x7ffec5d1ec88) at ../src/skel/glfw/glfw.cpp:1830
```

**Comment by strikersix23** [comment]
Ive been having a crash on windows like this

**Comment by erorcun** [comment]
did you try removing models/txd.img? then game will auto generate one at the start

**Comment by kattjevfel** [comment]
> did you try removing models/txd.img? then game will auto generate one at the start

Doing that made it work, I thought txd.img was supplied with the game files and wasn't being changed this way.
Anyway I do believe there should be a more elegant solution than this.
