### ISSUE TITLE
[miami] Segmentation fault when viewing the Street Race map at A+B Auto

### ISSUE THREAD

**Issue by consolethinks** [GTAmodding/re3#859]
Game crashes with a segmentation fault:
```
Thread 1 "reVC" received signal SIGSEGV, Segmentation fault.
0x5689144a in RwTextureGetRaster (texture=0x41) at ../src/fakerw/fake.cpp:269
269     RwRaster *RwTextureGetRaster(const RwTexture *texture) { return texture->raster; }
```
Backtrace:
```
#0  0x5689144a in RwTextureGetRaster (texture=0x41) at ../src/fakerw/fake.cpp:269
#1  0x56824445 in CSprite2d::SetRenderState (this=0x56c8e92c <CTheScripts::ScriptSphereArray+332>)
    at ../src/render/Sprite2d.cpp:70
#2  0x56824563 in CSprite2d::Draw (this=0x56c8e92c <CTheScripts::ScriptSphereArray+332>, rect=..., col=...)
    at ../src/render/Sprite2d.cpp:87
#3  0x566cf6e3 in CHud::DrawAfterFade () at ../src/render/Hud.cpp:1469
#4  0x5689a52e in Render2dStuffAfterFade () at ../src/core/main.cpp:1147
#5  0x5689aa04 in Idle (arg=0x1) at ../src/core/main.cpp:1301
#6  0x5689acd6 in AppEventHandler (event=rsIDLE, param=0x1) at ../src/core/main.cpp:1408
#7  0x568a5690 in RsEventHandler (event=rsIDLE, param=0x1) at ../src/skel/skeleton.cpp:212
#8  0x56896bb1 in main (argc=1, argv=0xffffcd74) at ../src/skel/glfw/glfw.cpp:1887
```
Last message printed to the console: "Will try to delete a vehicle where a mission entity should be"

**Comment by TheOfficialFloW** [comment]
Should be fixed by https://github.com/GTAmodding/re3/commit/5e019ed9f84c5aef8d474d5c62eb92b1cf5d9362.
