### ISSUE TITLE
New saves causes segfault once loaded

### ISSUE THREAD

**Issue by kattjevfel** [GTAmodding/re3#969]
I can load old saves (from a month ago or so), but if I as much try make a new save and load that, the application segfaults.
Normally I'd try bisect this, but building with premake broke, and instead cmake now finally works, so that'd just be too much work atm.

```
Thread 1 "re3" received signal SIGSEGV, Segmentation fault.
0x00005555556eb3e2 in CTheZones::PointLiesWithinZone(CVector const*, CZone*) ()
(gdb) bt
#0  0x00005555556eb3e2 in CTheZones::PointLiesWithinZone(CVector const*, CZone*) ()
#1  0x00005555556eb643 in CTheZones::FindSmallestZonePositionILN(CVector const*) ()
#2  0x00005555556eb76f in CTheZones::GetZoneInfo(CVector const*, unsigned char) ()
#3  0x00005555556eb7d2 in CTheZones::GetZoneInfoForTimeOfDay(CVector const*, CZoneInfo*) ()
#4  0x00005555556d14a8 in CStreaming::StreamZoneModels(CVector const&) ()
#5  0x00005555556ce440 in CStreaming::Update() ()
#6  0x00005555556b7ae0 in CGame::Process() ()
#7  0x00005555556f1443 in Idle(void*) ()
#8  0x00005555556f1b30 in AppEventHandler ()
#9  0x00005555557f0b30 in RsEventHandler ()
#10 0x00005555557f0185 in main ()
```

Running re3 25d3066eae00ea0af66c0ea908f7bbddac806078 on Arch Linux

**Comment by Nick007J** [comment]
Fixed by https://github.com/GTAmodding/re3/commit/8e825fa629dc3a0d82d1bc3ea8807ac10c986c82
